# Generated by Django 5.0.7 on 2024-08-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_schedule_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available_date',
            field=models.DateField(default=False),
        ),
    ]
