# Generated by Django 5.0.7 on 2024-08-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_date',
            field=models.DateField(),
        ),
    ]
